# Generated by Django 5.2.4 on 2025-08-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nota',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
