# Generated by Django 5.2.7 on 2025-10-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_nota_nota_nota_nota1_nota_nota2_nota_nota3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(default='Nome Padrão', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='nome_completo',
            field=models.CharField(default='Nome Padrão', max_length=255),
            preserve_default=False,
        ),
    ]
